In [20]:
import torch.nn as nn
import torch

In [3]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)

        self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)
    
    def forward(self, t):
        #TODO
        #implement the forward pass
        return t

In [4]:
network = Network()
print(network)

Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)


In [5]:
network.conv1

Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))

In [6]:
network.conv2

Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))

In [7]:
network.fc1

Linear(in_features=192, out_features=120, bias=True)

In [8]:
network.fc2

Linear(in_features=120, out_features=60, bias=True)

In [9]:
network.out

Linear(in_features=60, out_features=10, bias=True)

In [11]:
#This is from OOP from Pytorch with hidden Weights. This is updated when learning, when the loss function is minimized. The Parameter class extends torch.Tensor
network.conv1.weight

Parameter containing:
tensor([[[[-0.1033,  0.0622,  0.1497, -0.1884,  0.0516],
          [-0.0554, -0.1546, -0.1449, -0.0084,  0.0269],
          [ 0.0131,  0.1053, -0.1265,  0.0973, -0.0023],
          [-0.1985,  0.0222,  0.1934,  0.0588, -0.1528],
          [-0.0476,  0.1769,  0.0611, -0.0675,  0.1164]]],


        [[[ 0.1069,  0.0623, -0.0553,  0.0619, -0.0700],
          [-0.0465, -0.1585,  0.1221, -0.1780,  0.1015],
          [ 0.0815,  0.1276, -0.1221,  0.0244, -0.1538],
          [ 0.0128,  0.1550,  0.0725, -0.0350,  0.1404],
          [-0.0810, -0.0566, -0.1441,  0.1195,  0.1723]]],


        [[[-0.0993,  0.0450,  0.0268, -0.0524,  0.1701],
          [ 0.0299,  0.0774, -0.1472, -0.0541, -0.1652],
          [ 0.1260, -0.0201, -0.0414,  0.1410,  0.0355],
          [-0.1487,  0.1218,  0.0922,  0.1194,  0.1516],
          [ 0.0173, -0.0169, -0.1402, -0.0053, -0.1092]]],


        [[[ 0.1804,  0.1291,  0.1026,  0.1845,  0.0967],
          [-0.1591, -0.0484,  0.1992, -0.1671, -0.0646

In [12]:
#first rank => # of filters
#2nd rank => depth of each filter or # of input channels
#3rd and 4th is the height and width of the filter
network.conv1.weight.shape

torch.Size([6, 1, 5, 5])

In [13]:
network.conv2.weight.shape

torch.Size([12, 6, 5, 5])

In [14]:
#This is how you single out the Weight Tensor
network.conv2.weight[0].shape

torch.Size([6, 5, 5])

In [18]:
#Rank 2 tensors of linear layer
#Height is the output feature of the prevous Tensor
#Width is the number of input features
#This is a Weight Matrix. Weight Matrix * Input = Ouput.
network.fc1.weight.shape

torch.Size([120, 192])

In [16]:
network.fc2.weight.shape

torch.Size([60, 120])

In [17]:
network.out.weight.shape

torch.Size([10, 60])

In [21]:
in_features = torch.tensor([1,2,3,4], dtype=torch.float32)
print(in_features)

tensor([1., 2., 3., 4.])


In [23]:
weight_matrix = torch.tensor([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6]
], dtype=torch.float32)
weight_matrix

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [3., 4., 5., 6.]])

In [24]:
weight_matrix.matmul(in_features)

tensor([30., 40., 50.])

In [25]:
for param in network.parameters():
    print(param.shape)

torch.Size([6, 1, 5, 5])
torch.Size([6])
torch.Size([12, 6, 5, 5])
torch.Size([12])
torch.Size([120, 192])
torch.Size([120])
torch.Size([60, 120])
torch.Size([60])
torch.Size([10, 60])
torch.Size([10])


In [27]:
for name, param in network.named_parameters():
    print(name, '\t\t', param.shape)

conv1.weight 		 torch.Size([6, 1, 5, 5])
conv1.bias 		 torch.Size([6])
conv2.weight 		 torch.Size([12, 6, 5, 5])
conv2.bias 		 torch.Size([12])
fc1.weight 		 torch.Size([120, 192])
fc1.bias 		 torch.Size([120])
fc2.weight 		 torch.Size([60, 120])
fc2.bias 		 torch.Size([60])
out.weight 		 torch.Size([10, 60])
out.bias 		 torch.Size([10])
