In [2]:
import torch.nn as nn
import torch
#This generates a Weight Tensor 3x4
#This will be muliplied by a vector of 4x1, 1 is always the end dimension = 3x1 Matrix
fc = nn.Linear(in_features=4, out_features=3)

In [3]:
in_features = torch.tensor([1,2,3,4], dtype=torch.float32)

In [4]:
fc(in_features)
#Noticed that the Weight Matrix is randomly generated

tensor([-1.1635,  3.1326,  2.8741], grad_fn=<AddBackward0>)

In [5]:
weight_matrix = torch.tensor([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6]
], dtype=torch.float32)
fc.weight = nn.Parameter(weight_matrix)

In [6]:
fc(in_features)

tensor([29.7851, 39.6292, 49.7456], grad_fn=<AddBackward0>)

In [8]:
#y = Ax + b, b being the bias
fc = nn.Linear(in_features=4, out_features=3, bias=False)
fc.weight = nn.Parameter(weight_matrix)
fc(in_features)

tensor([30., 40., 50.], grad_fn=<SqueezeBackward3>)